### PR TITLE
CI workflow

### LINKED ISSUE #2: CI workflow
I'm going to attempt to set up a workflow for this project. This will include:

1. Setting up the Java 8 dependency
2. Installing the existing Gradle wrapper
3. Running the existing tests

### PR DESCRIPTION
**Pull request by OwenBC**
Implementing CI workflow with GitHub actions.

Closes #2

### CODE REVIEW

**Comment by OwenBC** [comment]
Build fail was expected. The failing test is a webdriver based test (setup for firefox specifically) and will require setup in order to run. However, it appears other than that the workflow succeeded, 20 of the 21 tests passed.

Also, I imagine we can probably configure tests to show more readable results in the GitHub interface.

**Comment by ketdougi** [comment]
I added WebDriverManager to the BrowserAcceptanceTest.java so that we can run the tests in that file however the builds are still failing. From looking at the error, it might be as the firefox version is incompatible with the selenium version. Would it be okay if i changed it from firefox to google chrome?

**Comment by OwenBC** [comment]
> I added WebDriverManager to the BrowserAcceptanceTest.java so that we can run the tests in that file however the builds are still failing. From looking at the error, it might be as the firefox version is incompatible with the selenium version. Would it be okay if i changed it from firefox to google chrome?

Sure. As long as it works, whatever is fine.

**Review by vijaivir — APPROVED** [review]
Great work on fixing the Build with Gradle failure!

**Pull request merged**
